name: test

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  testpy3:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Use the python version installed by Ubuntu 20.04 (version 3.8.5),
    # so we can use precompiled gdal and protobuf
    #- name: Set up Python 3.8
    #  uses: actions/setup-python@v3
    #  with:
    #    python-version: "3.8"
    - name: Install xmllint and GDAL
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils gdal-bin libgdal-dev python3-gdal
    - name: "Install python dependencies: cram and lxml"
      run: |
        python -m pip install --upgrade pip
        pip install cram lxml
    - name: Testing the code with cram, protobuf not installed
      run: |
        cram test/basic_usage.t
        cram test/osm_output.t
        cram test/pbf_output_no_protobuf.t
    - name: Install protobuf and osmctools
      run: sudo apt-get install -y libprotobuf-dev protobuf-compiler osmctools
    - name: "Install python dependencies: protobuf"
      run: |
        pip install --upgrade protobuf
    - name: Testing the code with cram, protobuf installed
      run: |
        cram test/pbf_output.t
